# Generated by Django 5.1.7 on 2025-03-11 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('kullanici_tipi', models.CharField(choices=[('yazar', 'Yazar'), ('editor', 'Editör'), ('hakem', 'Hakem')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_takip_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('baslik', models.CharField(max_length=255)),
                ('dosya', models.FileField(upload_to='makaleler/')),
                ('durum', models.CharField(choices=[('Yüklendi', 'Yüklendi'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Değerlendirildi', 'Değerlendirildi'), ('Yayınlandı', 'Yayınlandı')], default='Yüklendi', max_length=50)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makaleler', to='makale.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='LogKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tipi', models.CharField(choices=[('yuklendi', 'Yüklendi'), ('anonimlestirildi', 'Anonimleştirildi'), ('degerlendirildi', 'Değerlendirildi'), ('yayınlandı', 'Yayınlandı')], max_length=50)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degerlendirme_icerik', models.TextField(blank=True, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('hakem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='makale.kullanici')),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
        migrations.CreateModel(
            name='Anonimlestirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonim_bilgiler', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonimlestirmeler', to='makale.kullanici')),
                ('makale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale')),
            ],
        ),
    ]
