# Generated by Django 5.1.7 on 2025-03-14 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0003_mesaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='atanan_hakem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hakem_atanan_makaleler', to='makale.kullanici'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='durum',
            field=models.CharField(choices=[('Yüklendi', 'Yüklendi'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Değerlendirilmeye Gönderildi', 'Değerlendirilmeye Gönderildi'), ('Değerlendirildi', 'Değerlendirildi'), ('Yayınlandı', 'Yayınlandı')], default='Yüklendi', max_length=50),
        ),
    ]
