# Generated by Django 5.1.7 on 2025-03-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0005_makale_ozet_makale_yuklenme_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='ilgi_alanlari',
            field=models.TextField(blank=True, null=True),
        ),
    ]
