# Generated by Django 5.1.7 on 2025-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0006_kullanici_ilgi_alanlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonimlestirme',
            name='orijinal_dosya',
            field=models.FileField(blank=True, null=True, upload_to='makaleler/orijinal_kopya/'),
        ),
        migrations.AddField(
            model_name='degerlendirme',
            name='kilitli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='makale',
            name='anonim_dosya',
            field=models.FileField(blank=True, null=True, upload_to='makaleler/anonim/'),
        ),
        migrations.AlterField(
            model_name='logkaydi',
            name='islem_tipi',
            field=models.CharField(choices=[('yuklendi', 'Yüklendi'), ('anonimlestirildi', 'Anonimleştirildi'), ('hakeme_gonderildi', 'Hakeme Gönderildi'), ('hakem_degerlendirdi', 'Hakem Değerlendirdi'), ('editor_geri_yukledi', 'Editör Geri Yükledi'), ('yayınlandı', 'Yayınlandı')], max_length=50),
        ),
        migrations.AlterField(
            model_name='makale',
            name='dosya',
            field=models.FileField(upload_to='makaleler/orijinal/'),
        ),
        migrations.AlterField(
            model_name='makale',
            name='durum',
            field=models.CharField(choices=[('Yüklendi', 'Yüklendi'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Değerlendirmeye Gönderildi', 'Değerlendirmeye Gönderildi'), ('Değerlendirildi', 'Değerlendirildi'), ('Yayınlandı', 'Yayınlandı')], default='Yüklendi', max_length=50),
        ),
    ]
