# Generated by Django 5.1.7 on 2025-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0011_alter_makale_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='sha256_ozet',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
