# Generated by Django 5.1.7 on 2025-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0013_remove_makale_sha256_ozet'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonimlestirme',
            name='sifreli_veriler',
            field=models.TextField(blank=True, null=True),
        ),
    ]
