# Generated by Django 5.1.7 on 2025-03-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='alan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
