# Generated by Django 5.1.7 on 2025-03-14 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0004_makale_atanan_hakem_alter_makale_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='ozet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makale',
            name='yuklenme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
