# Generated by Django 5.1.7 on 2025-03-19 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0007_anonimlestirme_orijinal_dosya_degerlendirme_kilitli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degerlendirme',
            name='puan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='degerlendirme_icerik',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='makale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirmeler', to='makale.makale'),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='tarih',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
