# Generated by Django 5.1.7 on 2025-03-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0008_degerlendirme_puan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degerlendirme',
            name='degerlendirme_icerik',
            field=models.TextField(default='Henüz değerlendirme yapılmamış.'),
        ),
    ]
