# Generated by Django 5.1.7 on 2025-03-20 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0009_alter_degerlendirme_degerlendirme_icerik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degerlendirme',
            name='puan',
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='degerlendirme_icerik',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='makale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makale.makale'),
        ),
        migrations.AlterField(
            model_name='degerlendirme',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
