# Generated by Django 5.1.7 on 2025-03-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0010_remove_degerlendirme_puan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='durum',
            field=models.CharField(choices=[('Yüklendi', 'Yüklendi'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Değerlendirmeye Gönderildi', 'Değerlendirmeye Gönderildi'), ('Değerlendirildi', 'Değerlendirildi'), ('Revize Edildi', 'Revize Edildi'), ('Yayınlandı', 'Yayınlandı')], default='Yüklendi', max_length=50),
        ),
    ]
