# Generated by Django 5.1.7 on 2025-03-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0012_makale_sha256_ozet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='sha256_ozet',
        ),
    ]
