# Generated by Django 5.1.7 on 2025-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makale', '0014_anonimlestirme_sifreli_veriler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logkaydi',
            name='islem_tipi',
            field=models.CharField(choices=[('yuklendi', 'Yüklendi'), ('anonimlestirildi', 'Anonimleştirildi'), ('hakeme_gonderildi', 'Hakeme Gönderildi'), ('hakem_degerlendirdi', 'Hakem Değerlendirdi'), ('anonim_cozuldu', 'Anonimlik Çözüldü'), ('yazara_gonderildi', 'Yazara Gönderildi'), ('editor_geri_yukledi', 'Editör Geri Yükledi'), ('yayınlandı', 'Yayınlandı')], max_length=50),
        ),
        migrations.AlterField(
            model_name='makale',
            name='durum',
            field=models.CharField(choices=[('Yüklendi', 'Yüklendi'), ('Anonimleştirildi', 'Anonimleştirildi'), ('Değerlendirmeye Gönderildi', 'Değerlendirmeye Gönderildi'), ('Değerlendirildi', 'Değerlendirildi'), ('Değerlendirildi ve Anonimlik Çözüldü', 'Değerlendirildi ve Anonimlik Çözüldü'), ('Değerlendirildi - Anonimlik Çözüldü', 'Değerlendirildi - Anonimlik Çözüldü'), ('Anonimlik Çözüldü - Değerlendirildi', 'Anonimlik Çözüldü - Değerlendirildi'), ('Anonimlik Kaldırıldı', 'Anonimlik Kaldırıldı'), ('Yazara Gönderildi', 'Yazara Gönderildi'), ('Revize Edildi', 'Revize Edildi'), ('Yayınlandı', 'Yayınlandı')], default='Yüklendi', max_length=50),
        ),
    ]
